version: '3'
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "3000:80"
      
  src:
    build:
      dockerfile: Dockerfile.dev
      context: ./src
    container_name: blueMemories_backend
    volumes:
      - /app/node_modules
      - ./src:/app