version: '3'
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    container_name: frontend
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    stdin_open: true
    
  nginx:
    container_name: nginx
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "3000:80"
    # volumes:
    #   - ./nginx/html:/usr/share/nginx/html

  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    container_name: backend
    volumes:
      - /app/node_modules
      - ./src:/app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Bluememories
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234

  mysql:
    build: ./mysql
    restart: unless-stopped
    container_name: mysql
    ports:
      - "3300:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: BlueMemories
      MYSQL_ROOT_USER: root 
      MYSQL_PASSWORD: 1234
